# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'forumname', max_length=100)),
                ('short_name', models.CharField(default=b'shortforumname', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('parent', models.IntegerField(default=None, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('isHighlighted', models.BooleanField(default=False)),
                ('isEdited', models.BooleanField(default=False)),
                ('isSpam', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('message', models.TextField(default=b'message', max_length=500)),
                ('points', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('short_name', models.CharField(default=b'shortforumname', max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(default=b'title', max_length=50)),
                ('slug', models.CharField(default=b'title', max_length=50)),
                ('message', models.TextField(default=b'message', max_length=500)),
                ('isClosed', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('short_name', models.CharField(default=b'shortforumname', max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(default=b'about', max_length=700)),
                ('follow', models.ManyToManyField(to='subdapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Post_Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default=b'shortforumname', max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='subscribe',
            field=models.ManyToManyField(related_name='thread_user_subs', to='subdapp.User'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_create', to='subdapp.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.Thread'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.User'),
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdapp.User'),
        ),
    ]
